{
  "extends": ["spectral:asyncapi"],
  "rules": {
    "aap2-channel-must-have-version": {
      "given": "$.channels",
      "then":{
        "field": "@key",
        "function": "pattern",
        "functionOptions": {
          "match": ".*(\/v(.*[0-9])\/).*"
        }
      }
    },
    "aap2-payload-schema": {
      "given": "$.channels",
      "then":{
        "field": "@key",
        "function": "pattern",
        "functionOptions": {
          "match": ".*(\/v(.*[0-9])\/).*"
        }
      }
    }
  }  
}