---
extends: [[spectral:asyncapi, off]]
functions: [snake-case-properties, use-suffix-for-date-time, payload-with-no-additional-properties-unless-map]
rules:
  asyncapi-info-contact-properties: error
  asyncapi-info-description: error
  asyncapi-info-license-url: error
  asyncapi-operation-description: error
  asyncapi-parameter-description: error
  asyncapi-operation-operationId: error
  asyncapi-tag-description: error

  asyncapi-channel-must-have-version:
    given: "$.channels"
    description: 'Channel MUST have version number included in the topic. Example:
      "v1/channel/example"'
    severity: error
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: ".*(v(.*[0-9])).*"
  asyncapi-parameters-must-use-references:
    description: Channel parameters must be a reference
    given: $.channels.[*]
    severity: error
    resolved: false
    then:
      function: schema
      functionOptions:
        schema:
          properties:
            parameters:
              additionalProperties:
                type: object
                required:
                  - $ref
  asyncapi-messages-must-use-references:
    description: Operation messages must be a reference
    given: $.channels.[*][subscribe,publish].message
    severity: error
    resolved: false
    then:
      function: schema
      functionOptions:
        schema: 
          if:
            required:
              - oneOf
          then:
            properties: 
              oneOf:
                type: array
                items:
                  type: object
                  required:
                    - $ref
          else:
            type: object
            required:
              - $ref
  asyncapi-properties-must-follow-snake-case:
    given: $.channels.[*][subscribe,publish].message..properties
    severity: error
    then:
      function: snake-case-properties
  asyncapi-date-time-must-use-at-suffix:
    given: $.channels.[*][subscribe,publish].message..properties
    severity: error
    then:
      function: use-suffix-for-date-time
  asyncapi-payload-with-no-additional-properties-unless-map:
    given: $.channels.[*][subscribe,publish].message..payload.@object()
    severity: error
    then:
      function: payload-with-no-additional-properties-unless-map
  asyncapi-message-payload-must-have-root-level-object:
    description: Message payloads must at the root be an object
    given: $.channels.[*][subscribe,publish].message..payload
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          properties:
            type:
              const: "object"