name: Bump release rust game API
env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - documents/components/**
      - documents/rust.asyncapi.json
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Automated Version Bump
        id: version_bump
        uses: jonaslagoni/gh-action-asyncapi-document-bump@main
        env:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'
        with:
          path-to-asyncapi: ./documents/rust.asyncapi.json
          skip-tag: 'true'
          skip-commit: 'true'
          commit-message: 'chore\(release\): rust API v{{version}}'
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Install dependencies
        run: npm install
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Bundle documents
        run: npm run bundle
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Create Pull Request with bumped version
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_TOKEN }}'
          commit-message: 'chore(release): rust API v${{steps.version_bump.outputs.newVersion}}'
          committer: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          author: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          title: 'chore(release): rust API v${{steps.version_bump.outputs.newVersion}}'
          body: Version bump Rust API
          branch: 'version-bump/rust-v${{steps.version_bump.outputs.newVersion}}'
