on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GENERATOR_ACCESS }}
          repository: 'EventstackTech/rust-public-client-typescript'
          path: './typescript-client'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g @asyncapi/generator
      - run: ag ./Rust_server.json @asyncapi/ts-nats-template --output ./typescript-client --force-write
      - working-directory: ./typescript-client
        name: 'Push typescript client'
        run: |
          git config user.name jonaslagoni
          git config user.email jonas-lt@live.dk
          git add .
          git commit -m "Generated new client"
          git push