name: "Test PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PR title MUST follow conventional commits
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List AsyncAPI files
        uses: 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install node dependencies
        run: npm install
      - name: Lint AsyncAPI files
        run: npm run lint
      - name: Should be able to bundle files
        run: npm run bundle