on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Using another action for AsyncAPI for validation
      - name: Validating AsyncAPI document
        uses: WaleedAshraf/asyncapi-github-action@v1
        with:
          filepath: ./Rust_server.json