on: 
  push:
    paths:
      - 'components/**'
      - 'rust_processor.json'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Auto update generated client
          token: ${{ secrets.GENERATOR_ACCESS }}
          repo: EventGamingAPI/ts-nats-processor-library
