on: 
  push:
    branches:
      - main
    paths:
      - 'documents/components/**'
      - 'documents/rust_processor.asyncapi.json'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Auto update generated client
          token: ${{ secrets.GENERATOR_ACCESS }}
          repo: EventGamingAPI/ts-nats-processor-library
